// the initial value is included
export enum AGE_RANGE {
  ZERO_TO_TEN = 'ZERO_TO_TEN',
  TEN_TO_TWENTY = 'TEN_TO_TWENTY',
  TWENTY_TO_THIRTY = 'TWENTY_TO_THIRTY',
  THIRTY_TO_FOURTY = 'THIRTY_TO_FOURTY',
  FOURTY_TO_FIFTY = 'FOURTY_TO_FIFTY',
  FIFTY_TO_SIXTY = 'FIFTY_TO_SIXTY',
  SIXTY_TO_SEVENTY = 'SIXTY_TO_SEVENTY',
  SEVENTY_TO_EIGHTY = 'SEVENTY_TO_EIGHTY',
  EIGHTY_TO_NINETY = 'EIGHTY_TO_NINETY',
  NINETY_TO_HUNDRED = 'NINETY_TO_HUNDRED',
  OLDER_THAN_HUNDRED = 'OLDER_THAN_HUNDRED',
  UNKOWN_AGE = 'UNKOWN_AGE',
}

export enum GROUP_BY {
  ALPHABET = 'ALPHABET',
  NATIONALITY = 'NATIONALITY',
  AGE_RANGE = 'AGE_RANGE',
}
